---
- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add docker rep
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker-official-stable
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      # - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce
    state: present

- name: Add vagrant user to docker goup
  user:
    name: vagrant
    groups: docker
    append: true

# FIXME:
- name: Inject storage driver into daemon configuration
  copy:
    content: '{"storage-driver": "overlay2"}'
    dest: /etc/docker/daemon.json
    mode: 0644
  notify: restart docker

# done auto-magically as part of install, ought to part of handlers anyway
# - name: Make docker a service
#   service:
#     name: docker
#     enabled: true
