# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  FileUtils.mkdir_p './opt/eco'

  config.vm.box = "bento/ubuntu-18.04"

  # eco server
  config.vm.network "forwarded_port", guest: 3000, host: 3000, protocol: "udp"
  config.vm.network "forwarded_port", guest: 3001, host: 3001, protocol: "tcp"

  config.vm.synced_folder ".", "/src"
  config.vm.synced_folder "./opt/eco", "/opt/eco"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2000"
  end

  config.vm.provision "shell", path: "bootstrap-eco-server.sh"

end
